
DROP TABLE ADDFIELDS CASCADE CONSTRAINTS ; 

CREATE TABLE ADDFIELDS ( 
  ID_NODE    NUMBER (5)    NOT NULL, 
  ID_FIELD   NUMBER (6)    NOT NULL, 
  ID_PROP    NUMBER (4)    NOT NULL, 
  ID_OBJECT  NUMBER (4)    NOT NULL, 
  VALUE      VARCHAR2 (30), 
  NAME       VARCHAR2 (20), 
  VALUE2     VARCHAR2 (50), 
  PRIMARY KEY ( ID_FIELD, ID_NODE, ID_PROP, ID_OBJECT ) 
    USING INDEX 
     TABLESPACE SYSTEM PCTFREE 10
     STORAGE ( INITIAL 65536 ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE INDEX XIF38ADDFIELDS ON 
  "BQRK".ADDFIELDS(ID_PROP, ID_OBJECT) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE ADDOBJECTS CASCADE CONSTRAINTS ; 

CREATE TABLE ADDOBJECTS ( 
  ID_ADDOBJ  NUMBER (9)    NOT NULL, 
  ID_PARENT  NUMBER (9)    NOT NULL, 
  ID_OBJECT  NUMBER (4), 
  PRIMARY KEY ( ID_ADDOBJ, ID_PARENT ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE INDEX XIF34ADDOBJECTS ON 
  "BQRK".ADDOBJECTS(ID_OBJECT) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE UNIQUE INDEX XPKADDOBJECTS ON 
  "BQRK".ADDOBJECTS(ID_ADDOBJ, ID_PARENT) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE CONCENTRATOR_POINTS CASCADE CONSTRAINTS ; 

CREATE TABLE CONCENTRATOR_POINTS ( 
  ID_CON                NUMBER (7)    NOT NULL, 
  ID_CONCENTRATOR       NUMBER (7)    NOT NULL, 
  NAME_CONCENTRATOR     VARCHAR2 (128)  NOT NULL, 
  CONCENTRATOR_ADDRESS  VARCHAR2 (5)  DEFAULT 1 NOT NULL, 
  COMMENTS              VARCHAR2 (255), 
  TYPE                  VARCHAR2 (5)  NOT NULL, 
  PRIMARY KEY ( ID_CONCENTRATOR, ID_CON ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE UNIQUE INDEX PK_CONCENT_ID ON 
  "BQRK".CONCENTRATOR_POINTS(ID_CONCENTRATOR, ID_CON) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE INDEX XIF16CONCENTRATOR_POINTS ON 
  "BQRK".CONCENTRATOR_POINTS(ID_CON) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE CON_POINTS CASCADE CONSTRAINTS ; 

CREATE TABLE CON_POINTS ( 
  ID_IST        NUMBER (4), 
  ID_CON        NUMBER (7)    NOT NULL, 
  CON_TYPE      VARCHAR2 (5), 
  CON_NAME      VARCHAR2 (128)  NOT NULL, 
  STREET        VARCHAR2 (50)  DEFAULT 0, 
  IST_PIT       VARCHAR2 (20)  DEFAULT 0, 
  PHONE_NUMBER  VARCHAR2 (20), 
  IP_ADDRESS    VARCHAR2 (20), 
  PORT_NUM      VARCHAR2 (10), 
  DOM           VARCHAR2 (5), 
  COMMENTS      VARCHAR2 (1024), 
  DIST          VARCHAR2 (128)  DEFAULT 0, 
  PIC           BLOB, 
  PIC2          BLOB, 
  PIC3          BLOB, 
  PIC4          BLOB, 
  PIC5          BLOB, 
  PIC1          BLOB, 
  PIC6          BLOB, 
  PIC7          BLOB, 
  PRIMARY KEY ( ID_CON ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE UNIQUE INDEX PK_CON_POINTS ON 
  "BQRK".CON_POINTS(ID_CON) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE INDEX XIF28CON_POINTS ON 
  "BQRK".CON_POINTS(ID_IST) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE COUNTERS CASCADE CONSTRAINTS ; 

CREATE TABLE COUNTERS ( 
  ID_COUNTER       NUMBER (7)    NOT NULL, 
  ID_CONCENTRATOR  NUMBER (7)    NOT NULL, 
  ID_CON           NUMBER (7)    NOT NULL, 
  COUNTER_NAME     VARCHAR2 (128), 
  TYPE_ID          NUMBER (7), 
  STREET           VARCHAR2 (100)  DEFAULT 0, 
  DOM              VARCHAR2 (20), 
  FLAT             VARCHAR2 (8), 
  SERIAL_NUMBER    VARCHAR2 (30), 
  COUNTER_ADDRESS  NUMBER (5)    DEFAULT 0 NOT NULL, 
  COMMENTS         VARCHAR2 (255), 
  TEHN_ADDRESS     NVARCHAR2 (400), 
  OVERFLOW_RATE    NUMBER (6), 
  LAST_POK         NUMBER (15,6) DEFAULT 0, 
  DATE_LAST_POK    DATE, 
  IS_CAN           NUMBER (2)    DEFAULT 0, 
  FLAG             INTEGER       DEFAULT 0, 
  IS_WATER         INTEGER       DEFAULT 0, 
  DATE_CREATE      DATE          DEFAULT sysdate, 
  DIST             VARCHAR2 (64), 
  LAST_POK_CON     NUMBER, 
  LAST_POKT1       NUMBER (15,6) DEFAULT 0, 
  LAST_POKT2       NUMBER (15,6) DEFAULT 0, 
  LAST_POKT3       NUMBER (15,6) DEFAULT 0, 
  LAST_POKT4       NUMBER (15,6) DEFAULT 0, 
  ACTUAL           INTEGER       DEFAULT 0 NOT NULL, 
  DOBAV            NUMBER (10)   DEFAULT 0, 
  KOEF             VARCHAR2 (10)  DEFAULT 0.1, 
  LAST_AVG_RASH    NUMBER (5,2), 
  PRIMARY KEY ( ID_COUNTER, ID_CONCENTRATOR, ID_CON ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE INDEX XIF21COUNTERS ON 
  "BQRK".COUNTERS(ID_CONCENTRATOR, ID_CON) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE INDEX XIF26COUNTERS ON 
  "BQRK".COUNTERS(TYPE_ID) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE UNIQUE INDEX XPKCOUNTERS ON 
  "BQRK".COUNTERS(ID_COUNTER, ID_CONCENTRATOR, ID_CON) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE ERRORS CASCADE CONSTRAINTS ; 

CREATE TABLE ERRORS ( 
  SERIAL_NUMBER  VARCHAR2 (20), 
  COUNTER_NAME   VARCHAR2 (128), 
  ERROR_TEXT     VARCHAR2 (50), 
  WDATE          DATE          DEFAULT sysdate, 
  SUMM           VARCHAR2 (10))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 

DROP TABLE ERRORS_TEMP CASCADE CONSTRAINTS ; 

CREATE GLOBAL TEMPORARY TABLE ERRORS_TEMP ( 
  SERIAL_NUMBER  VARCHAR2 (20), 
  COUNTER_NAME   VARCHAR2 (128), 
  ERROR_TEXT     VARCHAR2 (50), 
  WDATE          DATE          DEFAULT sysdate, 
  SUMM           VARCHAR2 (10)) ON COMMIT PRESERVE ROWS; 

DROP TABLE GRID CASCADE CONSTRAINTS ; 

CREATE TABLE GRID ( 
  ID_SCHEDULE  NUMBER (20)   NOT NULL, 
  ID_NODE      NUMBER (20)   NOT NULL, 
  ID_PARENT    NUMBER (20)   DEFAULT 0 NOT NULL, 
  ID_OBJECT    NUMBER (20)   NOT NULL, 
  TEXT         VARCHAR2 (100), 
  PRIMARY KEY ( ID_SCHEDULE, ID_NODE, ID_PARENT, ID_OBJECT ) 
    USING INDEX 
     TABLESPACE SYSTEM PCTFREE 10
     STORAGE ( INITIAL 65536 ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE INDEX XIF35GRID ON 
  "BQRK".GRID(ID_SCHEDULE) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE INTERFACE CASCADE CONSTRAINTS ; 

CREATE TABLE INTERFACE ( 
  ID_INTERFACE  NUMBER (4)    NOT NULL, 
  NUM_ROW       NUMBER (4)    NOT NULL, 
  ID_SCHEDULE   NUMBER (4)    NOT NULL, 
  COL_TITLE     VARCHAR2 (30)  DEFAULT 0 NOT NULL, 
  WIDTH         NUMBER (2)    DEFAULT 0 NOT NULL, 
  VAL           VARCHAR2 (20)  DEFAULT 0 NOT NULL, 
  ALIGN         VARCHAR2 (1)  DEFAULT 0, 
  FILTR         VARCHAR2 (50)  DEFAULT 0, 
  MON           NUMBER (2)    DEFAULT 0, 
  GOD           NUMBER (2)    DEFAULT 0, 
  PREC          NUMBER (4)    DEFAULT 0, 
  GRUP          VARCHAR2 (20)  DEFAULT 0, 
  PERCENT       VARCHAR2 (3)  DEFAULT 0, 
  PRIMARY KEY ( NUM_ROW, ID_INTERFACE, ID_SCHEDULE ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE INDEX XIF37INTERFACE ON 
  "BQRK".INTERFACE(ID_SCHEDULE) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE UNIQUE INDEX XPKINTERFACE ON 
  "BQRK".INTERFACE(NUM_ROW, ID_INTERFACE, ID_SCHEDULE) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE IST_PIT CASCADE CONSTRAINTS ; 

CREATE TABLE IST_PIT ( 
  ID_IST    NUMBER (4)    NOT NULL, 
  TP        VARCHAR2 (50)  NOT NULL, 
  COMMENTS  VARCHAR2 (255), 
  PRIMARY KEY ( ID_IST ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE UNIQUE INDEX PK_IST_PIT ON 
  "BQRK".IST_PIT(ID_IST) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE LOG CASCADE CONSTRAINTS ; 

CREATE TABLE LOG ( 
  ID_SCHEDULE  NUMBER (3)    NOT NULL, 
  ID_LOG       NUMBER (5)    NOT NULL, 
  DATE_LOG     DATE, 
  ID_STEP      NUMBER (6)    NOT NULL, 
  STEP_TIME    DATE, 
  MESSAGE      VARCHAR2 (200), 
  PRIMARY KEY ( ID_LOG, ID_SCHEDULE ) 
    USING INDEX 
     TABLESPACE SYSTEM PCTFREE 10
     STORAGE ( INITIAL 65536 ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE INDEX XIF36LOG ON 
  "BQRK".LOG(ID_SCHEDULE) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE MN_CHG_LOG CASCADE CONSTRAINTS ; 

CREATE TABLE MN_CHG_LOG ( 
  WDATE      DATE          DEFAULT to_date(sysdate,'DD/MM/YYYY') NOT NULL, 
  ID_OBJECT  NUMBER (10)   NOT NULL, 
  TEXT       VARCHAR2 (200))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 

DROP TABLE OBJECTS CASCADE CONSTRAINTS ; 

CREATE TABLE OBJECTS ( 
  ID_OBJECT   NUMBER (4)    NOT NULL, 
  NAME_OBJ    VARCHAR2 (50), 
  COMMENTS    VARCHAR2 (255), 
  SHORT_NAME  VARCHAR2 (100), 
  PRIMARY KEY ( ID_OBJECT ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE UNIQUE INDEX PK_OBJECTS ON 
  "BQRK".OBJECTS(ID_OBJECT) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE POKAZ CASCADE CONSTRAINTS ; 

CREATE TABLE POKAZ ( 
  ID_COUNTER       NUMBER (8)    NOT NULL, 
  ID_CONCENTRATOR  NUMBER (8), 
  ID_CON           NUMBER (8), 
  DATE_POK         DATE          DEFAULT to_date(sysdate,'DD/MM/YYYY') NOT NULL, 
  TARIF1           NUMBER (15,6), 
  TARIF2           NUMBER (15,6), 
  TARIF3           NUMBER (15,6), 
  TARIF4           NUMBER (15,6), 
  TARIF5           NUMBER (15,6), 
  SUMM             NUMBER (15,6), 
  COMMENTS         VARCHAR2 (255), 
  SERIAL_NUMBER    VARCHAR2 (20), 
  RASHOD           NUMBER (12,4), 
  FNP              NUMBER (12,4), 
  DELTA_DAYS       NUMBER (12), 
  PRIMARY KEY ( DATE_POK, ID_COUNTER ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE UNIQUE INDEX PK_POKAZ ON 
  "BQRK".POKAZ(DATE_POK, ID_COUNTER) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE INDEX XIF22POKAZ ON 
  "BQRK".POKAZ(ID_COUNTER, ID_CONCENTRATOR, ID_CON) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE INDEX XP_SERIAL_NUM ON 
  "BQRK".POKAZ(SERIAL_NUMBER) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE POKAZ_TEMP CASCADE CONSTRAINTS ; 

CREATE GLOBAL TEMPORARY TABLE POKAZ_TEMP ( 
  ID_COUNTER       NUMBER (8)    NOT NULL, 
  ID_CONCENTRATOR  NUMBER (8), 
  ID_CON           NUMBER (8), 
  DATE_POK         DATE          NOT NULL, 
  TARIF1           NUMBER (11,4), 
  TARIF2           NUMBER (11,4), 
  TARIF3           NUMBER (11,4), 
  TARIF4           NUMBER (11,4), 
  TARIF5           NUMBER (11,4), 
  SUMM             NUMBER (11,4), 
  COMMENTS         VARCHAR2 (255), 
  SERIAL_NUMBER    VARCHAR2 (20), 
  RASHOD           NUMBER (12,4), 
  FNP              NUMBER (12,4), 
  DELTA_DAYS       NUMBER (12)) ON COMMIT PRESERVE ROWS; 

DROP TABLE PROPS CASCADE CONSTRAINTS ; 

CREATE TABLE PROPS ( 
  ID_PROP    NUMBER (4)    NOT NULL, 
  ID_OBJECT  NUMBER (4)    NOT NULL, 
  NAME_PROP  VARCHAR2 (50), 
  PRIMARY KEY ( ID_PROP, ID_OBJECT ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE INDEX XIF31PROPS ON 
  "BQRK".PROPS(ID_OBJECT) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE UNIQUE INDEX XPKPROPS ON 
  "BQRK".PROPS(ID_PROP, ID_OBJECT) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE PROP_VALS CASCADE CONSTRAINTS ; 

CREATE TABLE PROP_VALS ( 
  ID_VAL     NUMBER (4)    NOT NULL, 
  ID_PROP    NUMBER (4)    NOT NULL, 
  ID_OBJECT  NUMBER (4)    NOT NULL, 
  NAME_VALS  VARCHAR2 (50), 
  COMMENTS   VARCHAR2 (255), 
  PRIMARY KEY ( ID_VAL, ID_PROP, ID_OBJECT ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE INDEX XIF32PROP_VALS ON 
  "BQRK".PROP_VALS(ID_PROP, ID_OBJECT) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 

CREATE UNIQUE INDEX XPKPROP_VALS ON 
  "BQRK".PROP_VALS(ID_VAL, ID_PROP, ID_OBJECT) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


DROP TABLE SCHEDULE CASCADE CONSTRAINTS ; 

CREATE TABLE SCHEDULE ( 
  ID_SCHEDULE    NUMBER (3)    NOT NULL, 
  NAME_SCHEDULE  VARCHAR2 (50)  NOT NULL, 
  CREATE_DATE    DATE          DEFAULT sysdate NOT NULL, 
  LAST_DATE      DATE          DEFAULT sysdate NOT NULL, 
  COMMENTS       NVARCHAR2 (510), 
  DEF_INT        NUMBER (1)    DEFAULT 1 NOT NULL, 
  TIME_OPROS     VARCHAR2 (8), 
  PRIMARY KEY ( ID_SCHEDULE ) 
    USING INDEX 
     TABLESPACE SYSTEM PCTFREE 10
     STORAGE ( INITIAL 65536 ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 

DROP TABLE STATUS CASCADE CONSTRAINTS ; 

CREATE TABLE STATUS ( 
  ID_STATUS    NUMBER (2)    NOT NULL, 
  NAME_STATUS  NVARCHAR2 (100)  NOT NULL, 
  CONSTRAINT PK_STATUS
  PRIMARY KEY ( ID_STATUS ) 
    USING INDEX 
     TABLESPACE SYSTEM PCTFREE 10
     STORAGE ( INITIAL 65536 ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 

DROP TABLE TYPE_COUNTERS CASCADE CONSTRAINTS ; 

CREATE TABLE TYPE_COUNTERS ( 
  TYPE_ID   NUMBER (3)    NOT NULL, 
  TYPE      VARCHAR2 (128)  NOT NULL, 
  COMMENTS  VARCHAR2 (255), 
  KOEFF     NUMBER (7), 
  PRIMARY KEY ( TYPE_ID ))
   TABLESPACE SYSTEM
   PCTFREE 10
   PCTUSED 40
   INITRANS 1
   MAXTRANS 255
  STORAGE ( 
   INITIAL 65536
   MINEXTENTS 1
   MAXEXTENTS 2147483645
   FREELISTS 1 FREELIST GROUPS 1 )
   NOCACHE; 


CREATE UNIQUE INDEX PK_TYPE_COUNTERS ON 
  "BQRK".TYPE_COUNTERS(TYPE_ID) 
  TABLESPACE SYSTEM PCTFREE 10  STORAGE(INITIAL 65536 ) 
; 


ALTER TABLE ADDFIELDS ADD 
 FOREIGN KEY (ID_PROP, ID_OBJECT) 
  REFERENCES BQRK.PROPS (ID_PROP, ID_OBJECT) ;

ALTER TABLE ADDOBJECTS ADD 
 FOREIGN KEY (ID_OBJECT) 
  REFERENCES BQRK.OBJECTS (ID_OBJECT) ;

ALTER TABLE CONCENTRATOR_POINTS ADD 
 FOREIGN KEY (ID_CON) 
  REFERENCES BQRK.CON_POINTS (ID_CON) ;

ALTER TABLE CON_POINTS ADD 
 FOREIGN KEY (ID_IST) 
  REFERENCES BQRK.IST_PIT (ID_IST) ;

ALTER TABLE COUNTERS ADD 
 FOREIGN KEY (TYPE_ID) 
  REFERENCES BQRK.TYPE_COUNTERS (TYPE_ID) ;

ALTER TABLE COUNTERS ADD 
 FOREIGN KEY (ID_CONCENTRATOR, ID_CON) 
  REFERENCES BQRK.CONCENTRATOR_POINTS (ID_CONCENTRATOR, ID_CON) ;

ALTER TABLE GRID ADD 
 FOREIGN KEY (ID_SCHEDULE) 
  REFERENCES BQRK.SCHEDULE (ID_SCHEDULE) ;

ALTER TABLE INTERFACE ADD 
 FOREIGN KEY (ID_SCHEDULE) 
  REFERENCES BQRK.SCHEDULE (ID_SCHEDULE) ;

ALTER TABLE LOG ADD 
 FOREIGN KEY (ID_SCHEDULE) 
  REFERENCES BQRK.SCHEDULE (ID_SCHEDULE) ;

ALTER TABLE POKAZ ADD  CONSTRAINT MYCONSTR
 FOREIGN KEY (ID_COUNTER, ID_CONCENTRATOR, ID_CON) 
  REFERENCES BQRK.COUNTERS (ID_COUNTER, ID_CONCENTRATOR, ID_CON) ;

ALTER TABLE PROPS ADD 
 FOREIGN KEY (ID_OBJECT) 
  REFERENCES BQRK.OBJECTS (ID_OBJECT) ;

ALTER TABLE PROP_VALS ADD 
 FOREIGN KEY (ID_PROP, ID_OBJECT) 
  REFERENCES BQRK.PROPS (ID_PROP, ID_OBJECT) ;

